In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [32]:
import pandas as pd

df = pd.read_excel(
    "data/Online_Retail.xlsx",
    engine="openpyxl",
    nrows=10000
)

print(df.shape)
df.head()

(10000, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [33]:
import pandas as pd

df = pd.read_excel(
    "data/Online_Retail.xlsx",
    engine="openpyxl"
)

print("Dataset Shape:", df.shape)

Dataset Shape: (541909, 8)

In [34]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [36]:
df.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

In [37]:
missing = df.isnull().sum()

missing_percentage = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percentage
})

missing_df

             Missing Values  Percentage
InvoiceNo                 0    0.000000
StockCode                 0    0.000000
Description            1454    0.268311
Quantity                  0    0.000000
InvoiceDate               0    0.000000
UnitPrice                 0    0.000000
CustomerID           135080   24.926694
Country                   0    0.000000

In [38]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 5268

In [39]:
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Negative UnitPrice:", (df["UnitPrice"] < 0).sum())

Negative Quantity: 10624
Negative UnitPrice: 2

In [40]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [41]:
df.duplicated().sum()

np.int64(5268)

In [42]:
(df["Quantity"] < 0).sum()

np.int64(10624)

In [43]:
(df["Quantity"] < 0).sum()

np.int64(10624)

In [44]:
df = df.drop_duplicates()

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
print("Sales:", (df["Quantity"] > 0).sum())
print("Returns:", (df["Quantity"] < 0).sum())

Sales: 526054
Returns: 10587

In [47]:
(df["UnitPrice"] < 0).sum()

np.int64(2)

In [48]:
(df["UnitPrice"] == 0).sum()

np.int64(2510)

In [49]:
df[df["UnitPrice"] < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [50]:
df = df[df["UnitPrice"] >= 0]

In [51]:
(df["UnitPrice"] < 0).sum()

np.int64(0)

In [52]:
(df["UnitPrice"] == 0).sum()

np.int64(2510)

In [53]:
df[df["UnitPrice"] == 0][
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice"]
].head(10)

     InvoiceNo StockCode Description  Quantity  UnitPrice
622     536414     22139         NaN        56        0.0
1970    536545     21134         NaN         1        0.0
1971    536546     22145         NaN         1        0.0
1972    536547     37509         NaN         1        0.0
1987    536549    85226A         NaN         1        0.0
1988    536550     85044         NaN         1        0.0
2024    536552     20950         NaN         1        0.0
2025    536553     37461         NaN         3        0.0
2026    536554     84670         NaN        23        0.0
2406    536589     21777         NaN       -10        0.0

In [54]:
df_clean = df[df["UnitPrice"] > 0].copy()

In [55]:
df_clean.shape

(534129, 8)

In [56]:
df_clean["Revenue"] = df_clean["Quantity"] * df_clean["UnitPrice"]

In [57]:
df_clean[["Quantity", "UnitPrice", "Revenue"]].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [58]:
df_clean["TransactionType"] = np.where(
    df_clean["Quantity"] < 0,
    "Return",
    "Sale"
)

In [59]:
df_clean["TransactionType"].value_counts()

TransactionType
Sale      524878
Return      9251
Name: count, dtype: int64

In [60]:
df_clean.groupby("TransactionType")["Revenue"].sum()

TransactionType
Return   -8.939797e+05
Sale      1.064211e+07
Name: Revenue, dtype: float64

In [61]:
df_clean["NetRevenue"] = df_clean["Revenue"]

In [62]:
sales_revenue = df_clean.loc[
    df_clean["TransactionType"] == "Sale", "Revenue"
].sum()

return_revenue = df_clean.loc[
    df_clean["TransactionType"] == "Return", "Revenue"
].sum()

net_revenue = sales_revenue + return_revenue

sales_revenue, return_revenue, net_revenue

(np.float64(10642110.804),
 np.float64(-893979.7300000001),
 np.float64(9748131.074))

In [63]:
df_clean["CustomerID"].isna().sum()

np.int64(132565)

In [64]:
df_customer = df_clean.dropna(subset=["CustomerID"]).copy()

In [65]:
df_customer.shape

(401564, 11)

In [66]:
df_customer["CustomerID"].isna().sum()

np.int64(0)

In [67]:
df_customer["CustomerID"].nunique()

4371

In [68]:
customer_revenue = (
    df_customer.groupby("CustomerID")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

customer_revenue.head(10)

CustomerID
14646.0    279489.02
18102.0    256438.49
17450.0    187322.17
14911.0    132458.73
12415.0    123725.45
14156.0    113214.59
17511.0     88125.38
16684.0     65892.08
13694.0     62690.54
15311.0     59284.19
Name: Revenue, dtype: float64

In [69]:
country_revenue = (
    df_clean.groupby("Country")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

country_revenue.head(10)

Country
United Kingdom    8189252.304
Netherlands        284661.540
EIRE               262993.380
Germany            221509.470
France             197317.110
Australia          137009.770
Switzerland         56363.050
Spain               54756.030
Belgium             40910.960
Sweden              36585.410
Name: Revenue, dtype: float64

In [70]:
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

In [71]:
df_clean["Month"] = df_clean["InvoiceDate"].dt.to_period("M").astype(str)

In [72]:
monthly_revenue = (
    df_clean.groupby("Month")["Revenue"]
    .sum()
)

In [73]:
monthly_revenue

Month
2010-12     746723.610
2011-01     558448.560
2011-02     497026.410
2011-03     682013.980
2011-04     492367.841
2011-05     722094.100
2011-06     689977.230
2011-07     680156.991
2011-08     703510.580
2011-09    1017596.682
2011-10    1069368.230
2011-11    1456145.800
2011-12     432701.060
Name: Revenue, dtype: float64

In [74]:
product_sales = (
    df_clean[df_clean["Quantity"] > 0]
    .groupby("Description")["Quantity"]
    .sum()
    .sort_values(ascending=False)
)

product_sales.head(10)

Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        78033
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54951
JUMBO BAG RED RETROSPOT               48371
WHITE HANGING HEART T-LIGHT HOLDER    37872
POPCORN HOLDER                        36749
PACK OF 72 RETROSPOT CAKE CASES       36396
ASSORTED COLOUR BIRD ORNAMENT         36362
RABBIT NIGHT LIGHT                    30739
MINI PAINT SET VINTAGE                26633
Name: Quantity, dtype: int64

In [75]:
product_revenue = (
    df_clean[df_clean["Quantity"] > 0]
    .groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

product_revenue.head(10)

Description
DOTCOM POSTAGE                        206248.77
REGENCY CAKESTAND 3 TIER              174156.54
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106236.72
PARTY BUNTING                          99445.23
JUMBO BAG RED RETROSPOT                94159.81
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
POSTAGE                                78101.88
Manual                                 77752.82
RABBIT NIGHT LIGHT                     66870.03
Name: Revenue, dtype: float64

In [76]:
exclude_items = ["DOTCOM POSTAGE", "POSTAGE", "Manual"]

product_revenue_clean = (
    df_clean[
        (df_clean["Quantity"] > 0) &
        (~df_clean["Description"].isin(exclude_items))
    ]
    .groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

product_revenue_clean.head(10)

Description
REGENCY CAKESTAND 3 TIER              174156.54
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106236.72
PARTY BUNTING                          99445.23
JUMBO BAG RED RETROSPOT                94159.81
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
RABBIT NIGHT LIGHT                     66870.03
PAPER CHAIN KIT 50'S CHRISTMAS         64875.59
ASSORTED COLOUR BIRD ORNAMENT          58927.62
CHILLI LIGHTS                          54096.36
Name: Revenue, dtype: float64

In [77]:
df_clean["InvoiceNo"].nunique()

23796

In [78]:
aov = net_revenue / df_clean["InvoiceNo"].nunique()
aov

np.float64(409.65418868717427)

In [79]:
sales_df = df_clean[df_clean["TransactionType"] == "Sale"].copy()

In [80]:
sales_orders = sales_df["InvoiceNo"].nunique()
sales_orders

19960

In [81]:
sales_revenue = sales_df["Revenue"].sum()

aov_sales = sales_revenue / sales_orders

aov_sales

np.float64(533.1718839679359)

In [82]:
customer_orders = (
    sales_df.groupby("CustomerID")["InvoiceNo"]
    .nunique()
)

In [83]:
customer_orders.mean()

np.float64(4.272014753342554)

In [84]:
repeat_customers = (customer_orders > 1).sum()
repeat_customers

np.int64(2845)

In [85]:
one_time_customers = (customer_orders == 1).sum()
one_time_customers

np.int64(1493)

In [86]:
repeat_customer_pct = repeat_customers / customer_orders.size * 100
repeat_customer_pct

np.float64(65.58321807284463)

In [87]:
return_rate = len(df_clean[df_clean["TransactionType"] == "Return"]) / len(df_clean) * 100
return_rate

1.7319786044195318

In [88]:
return_revenue_rate = abs(return_revenue) / sales_revenue * 100
return_revenue_rate

np.float64(8.400398628287014)

In [89]:
df_clean[["Quantity", "UnitPrice", "Revenue"]].describe()

            Quantity      UnitPrice        Revenue
count  534129.000000  534129.000000  534129.000000
mean        9.916818       4.695864      18.250518
std       216.452113      95.079189     380.945385
min    -80995.000000       0.001000 -168469.600000
25%         1.000000       1.250000       3.750000
50%         3.000000       2.100000       9.900000
75%        10.000000       4.130000      17.570000
max     80995.000000   38970.000000  168469.600000

In [90]:
Q1 = df_clean["Quantity"].quantile(0.25)
Q1

np.float64(1.0)

In [91]:
Q3 = df_clean["Quantity"].quantile(0.75)
Q3

np.float64(10.0)

In [92]:
IQR = Q3 - Q1
IQR

np.float64(9.0)

In [93]:
lower_bound = Q1 - 1.5 * IQR
lower_bound

np.float64(-12.5)

In [94]:
upper_bound = Q3 + 1.5 * IQR
upper_bound

np.float64(23.5)

In [95]:
quantity_outliers = df_clean[
    (df_clean["Quantity"] < lower_bound) |
    (df_clean["Quantity"] > upper_bound)
]

len(quantity_outliers)

57326

In [96]:
sales_quantity_outliers = sales_df[
    sales_df["Quantity"] > upper_bound
]

len(sales_quantity_outliers)

56253

In [97]:
sales_quantity_outliers[
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "Revenue"]
].sort_values("Quantity", ascending=False).head(10)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,Revenue
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,168469.60
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,77183.60
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,0.21,1008.00
206121,554868,22197,SMALL POPCORN HOLDER,4300,0.72,3096.00
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,0.82,3202.92
270885,560599,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,0.06,191.16
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40
433788,573995,16014,SMALL CHINESE STYLE SCISSOR,3000,0.32,960.00
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,1.45,4176.00

In [98]:
df_clean["Quantity_Outlier"] = np.where(
    df_clean["Quantity"] > upper_bound,
    "Yes",
    "No"
)

In [99]:
Q1_price = df_clean["UnitPrice"].quantile(0.25)
Q3_price = df_clean["UnitPrice"].quantile(0.75)

IQR_price = Q3_price - Q1_price

In [100]:
Q1_price = df_clean["UnitPrice"].quantile(0.25)
Q1_price

np.float64(1.25)

In [101]:
Q3_price = df_clean["UnitPrice"].quantile(0.75)
Q3_price

np.float64(4.13)

In [102]:
IQR_price = Q3_price - Q1_price
IQR_price

np.float64(2.88)

In [103]:
lower_price = Q1_price - 1.5 * IQR_price
upper_price = Q3_price + 1.5 * IQR_price

lower_price, upper_price

(np.float64(-3.0700000000000003), np.float64(8.45))

In [104]:
price_outliers = df_clean[
    df_clean["UnitPrice"] > upper_price
]

len(price_outliers)

39448

In [105]:
price_outliers[
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "Revenue"]
].sort_values("UnitPrice", ascending=False).head(10)

       InvoiceNo  StockCode      Description  Quantity  UnitPrice   Revenue
222681   C556445          M           Manual        -1   38970.00 -38970.00
524602   C580605  AMAZONFEE       AMAZON FEE        -1   17836.46 -17836.46
43702    C540117  AMAZONFEE       AMAZON FEE        -1   16888.02 -16888.02
43703    C540118  AMAZONFEE       AMAZON FEE        -1   16453.71 -16453.71
15017     537632  AMAZONFEE       AMAZON FEE         1   13541.33  13541.33
16356    C537651  AMAZONFEE       AMAZON FEE        -1   13541.33 -13541.33
15016    C537630  AMAZONFEE       AMAZON FEE        -1   13541.33 -13541.33
16232    C537644  AMAZONFEE       AMAZON FEE        -1   13474.79 -13474.79
524601   C580604  AMAZONFEE       AMAZON FEE        -1   11586.50 -11586.50
299982   A563185          B  Adjust bad debt         1   11062.06  11062.06

In [106]:
df_clean[
    df_clean["Description"].str.contains("AMAZON", case=False, na=False)
].shape

(34, 13)

In [107]:
df_clean[
    df_clean["Description"].str.contains("AMAZON", case=False, na=False)
][["InvoiceNo", "Description", "Quantity", "UnitPrice", "Revenue"]]

       InvoiceNo Description  Quantity  UnitPrice   Revenue
14514    C537600  AMAZON FEE        -1       1.00     -1.00
15016    C537630  AMAZON FEE        -1   13541.33 -13541.33
15017     537632  AMAZON FEE         1   13541.33  13541.33
16232    C537644  AMAZON FEE        -1   13474.79 -13474.79
16313    C537647  AMAZON FEE        -1    5519.25  -5519.25
16356    C537651  AMAZON FEE        -1   13541.33 -13541.33
16357    C537652  AMAZON FEE        -1    6706.71  -6706.71
43702    C540117  AMAZON FEE        -1   16888.02 -16888.02
43703    C540118  AMAZON FEE        -1   16453.71 -16453.71
96844    C544587  AMAZON FEE        -1    5575.28  -5575.28
96845    C544589  AMAZON FEE        -1    5258.77  -5258.77
124741   C546987  AMAZON FEE        -1    5693.05  -5693.05
124787   C546989  AMAZON FEE        -1    5225.03  -5225.03
135534    547901  AMAZON FEE         1     219.76    219.76
135590   C547904  AMAZON FEE        -1     219.76   -219.76
191385   C553354  AMAZON FEE        -1    5876.40  -5876.40
191386   C553355  AMAZON FEE        -1    7006.83  -7006.83
239250   C558036  AMAZON FEE        -1    5791.18  -5791.18
239251   C558037  AMAZON FEE        -1    4534.24  -4534.24
262413   C559915  AMAZON FEE        -1    4383.62  -4383.62
262414   C559917  AMAZON FEE        -1    6497.47  -6497.47
287103   C562062  AMAZON FEE        -1    4575.64  -4575.64
287150   C562086  AMAZON FEE        -1    6721.37  -6721.37
312092   C564340  AMAZON FEE        -1    4527.65  -4527.65
312246   C564341  AMAZON FEE        -1    6662.51  -6662.51
342611   C566889  AMAZON FEE        -1    5522.14  -5522.14
342635   C566899  AMAZON FEE        -1    7427.97  -7427.97
383495   C570025  AMAZON FEE        -1    5942.57  -5942.57
429248   C573549  AMAZON FEE        -1    5942.57  -5942.57
429249   C573550  AMAZON FEE        -1    2185.04  -2185.04
446434   C574897  AMAZON FEE        -1    5877.18  -5877.18
446533   C574902  AMAZON FEE        -1    8286.22  -8286.22
524601   C580604  AMAZON FEE        -1   11586.50 -11586.50
524602   C580605  AMAZON FEE        -1   17836.46 -17836.46

In [108]:
df_clean["TransactionCategory"] = np.where(
    df_clean["Description"].eq("AMAZON FEE"),
    "Amazon Fee",
    "Product"
)

In [109]:
df_clean["TransactionCategory"].value_counts()

TransactionCategory
Product       534095
Amazon Fee        34
Name: count, dtype: int64

In [110]:
df_clean[
    df_clean["Description"].isin([
        "Manual",
        "Adjust bad debt",
        "POSTAGE",
        "DOTCOM POSTAGE"
    ])
]["Description"].value_counts()

Description
POSTAGE            1252
DOTCOM POSTAGE      707
Manual              561
Adjust bad debt       1
Name: count, dtype: int64

In [111]:
non_product_items = [
    "AMAZON FEE",
    "POSTAGE",
    "DOTCOM POSTAGE",
    "Manual",
    "Adjust bad debt"
]

df_clean["TransactionCategory"] = np.where(
    df_clean["Description"].isin(non_product_items),
    "Non-Product",
    "Product"
)

In [112]:
df_clean["TransactionCategory"].value_counts()

TransactionCategory
Product        531574
Non-Product      2555
Name: count, dtype: int64

In [113]:

product_df = df_clean[
    df_clean["TransactionCategory"] == "Product"
].copy()

In [114]:
product_df.shape

(531574, 14)

In [115]:
product_sales_revenue = product_df[
    product_df["TransactionType"] == "Sale"
]["Revenue"].sum()

product_return_revenue = product_df[
    product_df["TransactionType"] == "Return"
]["Revenue"].sum()

product_sales_revenue, product_return_revenue

(np.float64(10255184.184000002), np.float64(-500039.15))

In [116]:
product_return_rate = (
    abs(product_return_revenue) / product_sales_revenue
) * 100

product_return_rate

np.float64(4.875964595352214)

In [117]:
unique_orders = product_df["InvoiceNo"].nunique()
unique_orders

23334

In [118]:
aov = (product_sales_revenue + product_return_revenue) / unique_orders
aov

np.float64(418.06569958001205)

In [119]:
total_items_sold = product_df[
    product_df["TransactionType"] == "Sale"
]["Quantity"].sum()

avg_items_per_order = total_items_sold / unique_orders

avg_items_per_order

np.float64(238.34644724436444)

In [120]:
order_quantity = product_df[
    product_df["TransactionType"] == "Sale"
].groupby("InvoiceNo")["Quantity"].sum()

In [121]:
median_items_per_order = order_quantity.median()
median_items_per_order

np.float64(152.0)

In [122]:
unique_products_per_order = product_df[
    product_df["TransactionType"] == "Sale"
].groupby("InvoiceNo")["StockCode"].nunique()

unique_products_per_order.median()

np.float64(15.0)

In [123]:
top_countries = (
    product_df[product_df["TransactionType"] == "Sale"]
    .groupby("Country")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_countries

Country
United Kingdom    8726832.534
Netherlands        283889.340
EIRE               276090.860
Germany            205381.150
France             184679.000
Australia          138103.810
Spain               55706.560
Switzerland         53065.600
Japan               37416.370
Belgium             36927.340
Name: Revenue, dtype: float64

In [124]:
monthly_product_revenue = (
    product_df[product_df["TransactionType"] == "Sale"]
    .groupby("Month")["Revenue"]
    .sum()
)

monthly_product_revenue

Month
2010-12     776329.950
2011-01     670654.460
2011-02     508081.540
2011-03     690591.840
2011-04     515914.661
2011-05     740487.330
2011-06     738233.990
2011-07     688802.671
2011-08     724708.160
2011-09    1029275.382
2011-10    1104093.970
2011-11    1453295.980
2011-12     614714.250
Name: Revenue, dtype: float64

In [125]:
top_products_revenue = (
    product_df[product_df["TransactionType"] == "Sale"]
    .groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products_revenue

Description
REGENCY CAKESTAND 3 TIER              174156.54
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106236.72
PARTY BUNTING                          99445.23
JUMBO BAG RED RETROSPOT                94159.81
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
RABBIT NIGHT LIGHT                     66870.03
PAPER CHAIN KIT 50'S CHRISTMAS         64875.59
ASSORTED COLOUR BIRD ORNAMENT          58927.62
CHILLI LIGHTS                          54096.36
Name: Revenue, dtype: float64

In [126]:
top10_revenue_share = (
    top_products_revenue.sum() / product_sales_revenue
) * 100

top10_revenue_share

np.float64(9.448279061742495)

In [127]:
customer_revenue = (
    product_df[product_df["TransactionType"] == "Sale"]
    .groupby("CustomerID")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

customer_revenue.head(10)

CustomerID
14646.0    279138.02
18102.0    259657.30
17450.0    194390.79
16446.0    168472.50
14911.0    140336.83
12415.0    124564.53
14156.0    117210.08
17511.0     91062.38
12346.0     77183.60
16029.0     72708.09
Name: Revenue, dtype: float64

In [128]:
top10_customer_share = (
    customer_revenue.head(10).sum() / product_sales_revenue
) * 100

top10_customer_share

np.float64(14.867837501922725)

In [129]:
customer_revenue.describe()

count      4335.000000
mean       2017.088499
std        8919.392095
min           3.750000
25%         304.250000
50%         663.610000
75%        1631.475000
max      279138.020000
Name: Revenue, dtype: float64

In [130]:
def customer_segment(revenue):
    if revenue <= 304.25:
        return "Low Value"
    elif revenue <= 1631.475:
        return "Medium Value"
    else:
        return "High Value"

customer_segments = customer_revenue.apply(customer_segment)

In [131]:
customer_segments.value_counts()

Revenue
Medium Value    2166
Low Value       1085
High Value      1084
Name: count, dtype: int64

In [132]:
customer_analysis = customer_revenue.reset_index()

customer_analysis["CustomerSegment"] = customer_analysis["Revenue"].apply(
    customer_segment
)

customer_analysis.head()

   CustomerID    Revenue CustomerSegment
0     14646.0  279138.02      High Value
1     18102.0  259657.30      High Value
2     17450.0  194390.79      High Value
3     16446.0  168472.50      High Value
4     14911.0  140336.83      High Value

In [133]:
segment_revenue = (
    customer_analysis
    .groupby("CustomerSegment")["Revenue"]
    .agg(["count", "sum", "mean", "median"])
    .sort_values("sum", ascending=False)
)

segment_revenue

                 count          sum         mean   median
CustomerSegment
High Value        1084  6918391.461  6382.279946  3012.53
Medium Value      2166  1634217.313   754.486294   663.71
Low Value         1085   191469.870   176.469926   173.90

In [134]:
customer_orders = (
    product_df[product_df["TransactionType"] == "Sale"]
    .groupby("CustomerID")["InvoiceNo"]
    .nunique()
)

customer_orders.describe()

count    4335.000000
mean        4.248212
std         7.646024
min         1.000000
25%         1.000000
50%         2.000000
75%         5.000000
max       206.000000
Name: InvoiceNo, dtype: float64

In [135]:
one_time_customers = (customer_orders == 1).sum()
repeat_customers = (customer_orders > 1).sum()

one_time_customers, repeat_customers

(np.int64(1505), np.int64(2830))

In [136]:
repeat_customer_rate = (
    repeat_customers / len(customer_orders)
) * 100

repeat_customer_rate

np.float64(65.28258362168397)

In [137]:
df_clean.isnull().sum()

InvoiceNo                   0
StockCode                   0
Description                 0
Quantity                    0
InvoiceDate                 0
UnitPrice                   0
CustomerID             132565
Country                     0
Revenue                     0
TransactionType             0
NetRevenue                  0
Month                       0
Quantity_Outlier            0
TransactionCategory         0
dtype: int64

In [138]:
df_clean.to_csv("online_retail_cleaned.csv", index=False)

In [139]:
df_clean.shape

(534129, 14)